### ISSUE TITLE
CSS row

### ISSUE THREAD

**Issue by martoio** [jimtrippe/teacozy#1]
There's no reason to have 2 separate classes. The code you have is identical for each row. Moreover, in the next CSS rule, you have ``.row1 h4 ..... .row2 h4`` and the CSS is the same for both (pretty much). You can easily have this as 1 class.

https://github.com/jimtrippe/teacozy/blob/938179bde141082aafd48f9e823a191161d7e2d0/resources/css/style.css#L116-L117

**Comment by jimtrippe** [comment]
I meant to collapse those but had different css attributes for each while testing visual effects.
