### ISSUE TITLE
Class names 2

### ISSUE THREAD

**Issue by martoio** [jimtrippe/teacozy#2]
Again, unless there's a clear reason to have a distinction of these classes, you can compress them down to 1 class that describes what they are. ``.tea-item`` for example
https://github.com/jimtrippe/teacozy/blob/938179bde141082aafd48f9e823a191161d7e2d0/resources/css/style.css#L126-L130

**Comment by jimtrippe** [comment]
I did that to keep track of each while I built the framework than inserted images and paths.  Noted.
