### ISSUE TITLE
Spans

### ISSUE THREAD

**Issue by martoio** [jimtrippe/teacozy#3]
I wouldn't really use a span in this instance. A span is intended primarily for text (it's an inline element). What you have here are supposed to be blocks, so a div would be appropriate. You could also use a ``<figure>`` element for that, although it's not exactly what it's meant for, but it is more semantic than a span.

https://github.com/jimtrippe/teacozy/blob/938179bde141082aafd48f9e823a191161d7e2d0/index.html#L40-L43

**Comment by jimtrippe** [comment]
Good advice, taken.  Thank you.
